const fs = require('fs');
const files = ['./src/data/csharp-tutorial-data.js', './src/data/aspnet-mvc-tutorial-data.js'];

files.forEach(file => {
    let content = fs.readFileSync(file, 'utf8');
    
    // Change back the property name
    content = content.replace(/_diagram_backup:/g, 'diagram:');
    
    // Process diagram strings
    content = content.replace(/diagram: \`([\s\S]*?)\`/g, (match, p1) => {
        let newChart = p1;
        // Remove literal newline generated by my previous replace
        newChart = newChart.replace(/\\n/g, ' ');
        // Remove <br> and <br/>
        newChart = newChart.replace(/<br\s*\/?>/gi, ' ');
        // Remove ampersands
        newChart = newChart.replace(/&/g, 'and');
        // Remove quotes around edge labels: -->|"text"| to -->|text|
        newChart = newChart.replace(/-->\|\"([^\"]*)\"\|/g, '-->|$1|');
        // Remove . in subgraph titles just in case
        newChart = newChart.replace(/subgraph (\w+) \[\"\.NET/g, 'subgraph $1 [\"NET');
        
        return 'diagram: `' + newChart + '`';
    });
    
    fs.writeFileSync(file, content);
});
